bucket: nadex-daily-results
public_bucket: market-data-prod.nadex.com
region: us-east-1
prefixes:
  historical: historical
  manifests: manifests
  logs: logs
mapping_file: ticker_from_description.csv